// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/quii/go-fakes-and-contracts/adapters/driven/persistence/sqlite/ent/ingredient"
	"github.com/quii/go-fakes-and-contracts/adapters/driven/persistence/sqlite/ent/pantry"
	"github.com/quii/go-fakes-and-contracts/adapters/driven/persistence/sqlite/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PantryUpdate is the builder for updating Pantry entities.
type PantryUpdate struct {
	config
	hooks    []Hook
	mutation *PantryMutation
}

// Where appends a list predicates to the PantryUpdate builder.
func (pu *PantryUpdate) Where(ps ...predicate.Pantry) *PantryUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetQuantity sets the "quantity" field.
func (pu *PantryUpdate) SetQuantity(i int) *PantryUpdate {
	pu.mutation.ResetQuantity()
	pu.mutation.SetQuantity(i)
	return pu
}

// AddQuantity adds i to the "quantity" field.
func (pu *PantryUpdate) AddQuantity(i int) *PantryUpdate {
	pu.mutation.AddQuantity(i)
	return pu
}

// SetIngredientID sets the "ingredient" edge to the Ingredient entity by ID.
func (pu *PantryUpdate) SetIngredientID(id int) *PantryUpdate {
	pu.mutation.SetIngredientID(id)
	return pu
}

// SetNillableIngredientID sets the "ingredient" edge to the Ingredient entity by ID if the given value is not nil.
func (pu *PantryUpdate) SetNillableIngredientID(id *int) *PantryUpdate {
	if id != nil {
		pu = pu.SetIngredientID(*id)
	}
	return pu
}

// SetIngredient sets the "ingredient" edge to the Ingredient entity.
func (pu *PantryUpdate) SetIngredient(i *Ingredient) *PantryUpdate {
	return pu.SetIngredientID(i.ID)
}

// Mutation returns the PantryMutation object of the builder.
func (pu *PantryUpdate) Mutation() *PantryMutation {
	return pu.mutation
}

// ClearIngredient clears the "ingredient" edge to the Ingredient entity.
func (pu *PantryUpdate) ClearIngredient() *PantryUpdate {
	pu.mutation.ClearIngredient()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PantryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PantryUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PantryUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PantryUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PantryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pantry.Table, pantry.Columns, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Quantity(); ok {
		_spec.SetField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedQuantity(); ok {
		_spec.AddField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if pu.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pantry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PantryUpdateOne is the builder for updating a single Pantry entity.
type PantryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PantryMutation
}

// SetQuantity sets the "quantity" field.
func (puo *PantryUpdateOne) SetQuantity(i int) *PantryUpdateOne {
	puo.mutation.ResetQuantity()
	puo.mutation.SetQuantity(i)
	return puo
}

// AddQuantity adds i to the "quantity" field.
func (puo *PantryUpdateOne) AddQuantity(i int) *PantryUpdateOne {
	puo.mutation.AddQuantity(i)
	return puo
}

// SetIngredientID sets the "ingredient" edge to the Ingredient entity by ID.
func (puo *PantryUpdateOne) SetIngredientID(id int) *PantryUpdateOne {
	puo.mutation.SetIngredientID(id)
	return puo
}

// SetNillableIngredientID sets the "ingredient" edge to the Ingredient entity by ID if the given value is not nil.
func (puo *PantryUpdateOne) SetNillableIngredientID(id *int) *PantryUpdateOne {
	if id != nil {
		puo = puo.SetIngredientID(*id)
	}
	return puo
}

// SetIngredient sets the "ingredient" edge to the Ingredient entity.
func (puo *PantryUpdateOne) SetIngredient(i *Ingredient) *PantryUpdateOne {
	return puo.SetIngredientID(i.ID)
}

// Mutation returns the PantryMutation object of the builder.
func (puo *PantryUpdateOne) Mutation() *PantryMutation {
	return puo.mutation
}

// ClearIngredient clears the "ingredient" edge to the Ingredient entity.
func (puo *PantryUpdateOne) ClearIngredient() *PantryUpdateOne {
	puo.mutation.ClearIngredient()
	return puo
}

// Where appends a list predicates to the PantryUpdate builder.
func (puo *PantryUpdateOne) Where(ps ...predicate.Pantry) *PantryUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PantryUpdateOne) Select(field string, fields ...string) *PantryUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pantry entity.
func (puo *PantryUpdateOne) Save(ctx context.Context) (*Pantry, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PantryUpdateOne) SaveX(ctx context.Context) *Pantry {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PantryUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PantryUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PantryUpdateOne) sqlSave(ctx context.Context) (_node *Pantry, err error) {
	_spec := sqlgraph.NewUpdateSpec(pantry.Table, pantry.Columns, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pantry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pantry.FieldID)
		for _, f := range fields {
			if !pantry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pantry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Quantity(); ok {
		_spec.SetField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedQuantity(); ok {
		_spec.AddField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if puo.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pantry{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pantry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
