// Code generated by ent, DO NOT EDIT.

package recipeingredient

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recipeingredient type in the database.
	Label = "recipe_ingredient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// EdgeRecipe holds the string denoting the recipe edge name in mutations.
	EdgeRecipe = "recipe"
	// EdgeIngredient holds the string denoting the ingredient edge name in mutations.
	EdgeIngredient = "ingredient"
	// Table holds the table name of the recipeingredient in the database.
	Table = "recipe_ingredients"
	// RecipeTable is the table that holds the recipe relation/edge.
	RecipeTable = "recipe_ingredients"
	// RecipeInverseTable is the table name for the Recipe entity.
	// It exists in this package in order to avoid circular dependency with the "recipe" package.
	RecipeInverseTable = "recipes"
	// RecipeColumn is the table column denoting the recipe relation/edge.
	RecipeColumn = "recipe_recipeingredient"
	// IngredientTable is the table that holds the ingredient relation/edge. The primary key declared below.
	IngredientTable = "recipe_ingredient_ingredient"
	// IngredientInverseTable is the table name for the Ingredient entity.
	// It exists in this package in order to avoid circular dependency with the "ingredient" package.
	IngredientInverseTable = "ingredients"
)

// Columns holds all SQL columns for recipeingredient fields.
var Columns = []string{
	FieldID,
	FieldQuantity,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "recipe_ingredients"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"recipe_recipeingredient",
}

var (
	// IngredientPrimaryKey and IngredientColumn2 are the table columns denoting the
	// primary key for the ingredient relation (M2M).
	IngredientPrimaryKey = []string{"recipe_ingredient_id", "ingredient_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RecipeIngredient queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByRecipeField orders the results by recipe field.
func ByRecipeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecipeStep(), sql.OrderByField(field, opts...))
	}
}

// ByIngredientCount orders the results by ingredient count.
func ByIngredientCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIngredientStep(), opts...)
	}
}

// ByIngredient orders the results by ingredient terms.
func ByIngredient(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIngredientStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecipeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecipeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RecipeTable, RecipeColumn),
	)
}
func newIngredientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IngredientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, IngredientTable, IngredientPrimaryKey...),
	)
}
