// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quii/go-fakes-and-contracts/adapters/persistence/sqlite/ent/ingredient"
	"github.com/quii/go-fakes-and-contracts/adapters/persistence/sqlite/ent/predicate"
	"github.com/quii/go-fakes-and-contracts/adapters/persistence/sqlite/ent/recipe"
	"github.com/quii/go-fakes-and-contracts/adapters/persistence/sqlite/ent/recipeingredient"
)

// RecipeIngredientUpdate is the builder for updating RecipeIngredient entities.
type RecipeIngredientUpdate struct {
	config
	hooks    []Hook
	mutation *RecipeIngredientMutation
}

// Where appends a list predicates to the RecipeIngredientUpdate builder.
func (riu *RecipeIngredientUpdate) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientUpdate {
	riu.mutation.Where(ps...)
	return riu
}

// SetQuantity sets the "quantity" field.
func (riu *RecipeIngredientUpdate) SetQuantity(i int) *RecipeIngredientUpdate {
	riu.mutation.ResetQuantity()
	riu.mutation.SetQuantity(i)
	return riu
}

// AddQuantity adds i to the "quantity" field.
func (riu *RecipeIngredientUpdate) AddQuantity(i int) *RecipeIngredientUpdate {
	riu.mutation.AddQuantity(i)
	return riu
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (riu *RecipeIngredientUpdate) SetRecipeID(id int) *RecipeIngredientUpdate {
	riu.mutation.SetRecipeID(id)
	return riu
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (riu *RecipeIngredientUpdate) SetNillableRecipeID(id *int) *RecipeIngredientUpdate {
	if id != nil {
		riu = riu.SetRecipeID(*id)
	}
	return riu
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (riu *RecipeIngredientUpdate) SetRecipe(r *Recipe) *RecipeIngredientUpdate {
	return riu.SetRecipeID(r.ID)
}

// AddIngredientIDs adds the "ingredient" edge to the Ingredient entity by IDs.
func (riu *RecipeIngredientUpdate) AddIngredientIDs(ids ...int) *RecipeIngredientUpdate {
	riu.mutation.AddIngredientIDs(ids...)
	return riu
}

// AddIngredient adds the "ingredient" edges to the Ingredient entity.
func (riu *RecipeIngredientUpdate) AddIngredient(i ...*Ingredient) *RecipeIngredientUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return riu.AddIngredientIDs(ids...)
}

// Mutation returns the RecipeIngredientMutation object of the builder.
func (riu *RecipeIngredientUpdate) Mutation() *RecipeIngredientMutation {
	return riu.mutation
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (riu *RecipeIngredientUpdate) ClearRecipe() *RecipeIngredientUpdate {
	riu.mutation.ClearRecipe()
	return riu
}

// ClearIngredient clears all "ingredient" edges to the Ingredient entity.
func (riu *RecipeIngredientUpdate) ClearIngredient() *RecipeIngredientUpdate {
	riu.mutation.ClearIngredient()
	return riu
}

// RemoveIngredientIDs removes the "ingredient" edge to Ingredient entities by IDs.
func (riu *RecipeIngredientUpdate) RemoveIngredientIDs(ids ...int) *RecipeIngredientUpdate {
	riu.mutation.RemoveIngredientIDs(ids...)
	return riu
}

// RemoveIngredient removes "ingredient" edges to Ingredient entities.
func (riu *RecipeIngredientUpdate) RemoveIngredient(i ...*Ingredient) *RecipeIngredientUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return riu.RemoveIngredientIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (riu *RecipeIngredientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, riu.sqlSave, riu.mutation, riu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (riu *RecipeIngredientUpdate) SaveX(ctx context.Context) int {
	affected, err := riu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (riu *RecipeIngredientUpdate) Exec(ctx context.Context) error {
	_, err := riu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riu *RecipeIngredientUpdate) ExecX(ctx context.Context) {
	if err := riu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riu *RecipeIngredientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeingredient.Table, recipeingredient.Columns, sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt))
	if ps := riu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := riu.mutation.Quantity(); ok {
		_spec.SetField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := riu.mutation.AddedQuantity(); ok {
		_spec.AddField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if riu.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riu.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if riu.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riu.mutation.RemovedIngredientIDs(); len(nodes) > 0 && !riu.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riu.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, riu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	riu.mutation.done = true
	return n, nil
}

// RecipeIngredientUpdateOne is the builder for updating a single RecipeIngredient entity.
type RecipeIngredientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecipeIngredientMutation
}

// SetQuantity sets the "quantity" field.
func (riuo *RecipeIngredientUpdateOne) SetQuantity(i int) *RecipeIngredientUpdateOne {
	riuo.mutation.ResetQuantity()
	riuo.mutation.SetQuantity(i)
	return riuo
}

// AddQuantity adds i to the "quantity" field.
func (riuo *RecipeIngredientUpdateOne) AddQuantity(i int) *RecipeIngredientUpdateOne {
	riuo.mutation.AddQuantity(i)
	return riuo
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (riuo *RecipeIngredientUpdateOne) SetRecipeID(id int) *RecipeIngredientUpdateOne {
	riuo.mutation.SetRecipeID(id)
	return riuo
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (riuo *RecipeIngredientUpdateOne) SetNillableRecipeID(id *int) *RecipeIngredientUpdateOne {
	if id != nil {
		riuo = riuo.SetRecipeID(*id)
	}
	return riuo
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (riuo *RecipeIngredientUpdateOne) SetRecipe(r *Recipe) *RecipeIngredientUpdateOne {
	return riuo.SetRecipeID(r.ID)
}

// AddIngredientIDs adds the "ingredient" edge to the Ingredient entity by IDs.
func (riuo *RecipeIngredientUpdateOne) AddIngredientIDs(ids ...int) *RecipeIngredientUpdateOne {
	riuo.mutation.AddIngredientIDs(ids...)
	return riuo
}

// AddIngredient adds the "ingredient" edges to the Ingredient entity.
func (riuo *RecipeIngredientUpdateOne) AddIngredient(i ...*Ingredient) *RecipeIngredientUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return riuo.AddIngredientIDs(ids...)
}

// Mutation returns the RecipeIngredientMutation object of the builder.
func (riuo *RecipeIngredientUpdateOne) Mutation() *RecipeIngredientMutation {
	return riuo.mutation
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (riuo *RecipeIngredientUpdateOne) ClearRecipe() *RecipeIngredientUpdateOne {
	riuo.mutation.ClearRecipe()
	return riuo
}

// ClearIngredient clears all "ingredient" edges to the Ingredient entity.
func (riuo *RecipeIngredientUpdateOne) ClearIngredient() *RecipeIngredientUpdateOne {
	riuo.mutation.ClearIngredient()
	return riuo
}

// RemoveIngredientIDs removes the "ingredient" edge to Ingredient entities by IDs.
func (riuo *RecipeIngredientUpdateOne) RemoveIngredientIDs(ids ...int) *RecipeIngredientUpdateOne {
	riuo.mutation.RemoveIngredientIDs(ids...)
	return riuo
}

// RemoveIngredient removes "ingredient" edges to Ingredient entities.
func (riuo *RecipeIngredientUpdateOne) RemoveIngredient(i ...*Ingredient) *RecipeIngredientUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return riuo.RemoveIngredientIDs(ids...)
}

// Where appends a list predicates to the RecipeIngredientUpdate builder.
func (riuo *RecipeIngredientUpdateOne) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientUpdateOne {
	riuo.mutation.Where(ps...)
	return riuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (riuo *RecipeIngredientUpdateOne) Select(field string, fields ...string) *RecipeIngredientUpdateOne {
	riuo.fields = append([]string{field}, fields...)
	return riuo
}

// Save executes the query and returns the updated RecipeIngredient entity.
func (riuo *RecipeIngredientUpdateOne) Save(ctx context.Context) (*RecipeIngredient, error) {
	return withHooks(ctx, riuo.sqlSave, riuo.mutation, riuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (riuo *RecipeIngredientUpdateOne) SaveX(ctx context.Context) *RecipeIngredient {
	node, err := riuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (riuo *RecipeIngredientUpdateOne) Exec(ctx context.Context) error {
	_, err := riuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riuo *RecipeIngredientUpdateOne) ExecX(ctx context.Context) {
	if err := riuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riuo *RecipeIngredientUpdateOne) sqlSave(ctx context.Context) (_node *RecipeIngredient, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeingredient.Table, recipeingredient.Columns, sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt))
	id, ok := riuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecipeIngredient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := riuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recipeingredient.FieldID)
		for _, f := range fields {
			if !recipeingredient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recipeingredient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := riuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := riuo.mutation.Quantity(); ok {
		_spec.SetField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := riuo.mutation.AddedQuantity(); ok {
		_spec.AddField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if riuo.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riuo.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if riuo.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riuo.mutation.RemovedIngredientIDs(); len(nodes) > 0 && !riuo.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riuo.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecipeIngredient{config: riuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, riuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	riuo.mutation.done = true
	return _node, nil
}
