// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ingredient is the predicate function for ingredient builders.
type Ingredient func(*sql.Selector)
